### ISSUE TITLE
[vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function

### ISSUE THREAD

**Issue by ikomom** [ymchun/vue-dynamic-form#3]
hello, i use this with my project, but it doesn't work. I also create a lib myself use @vue/composition-api,  and when i use it in another project, it error.
I find lost of solution, and your project is very simliar to mine. 
Do you have any advice? [https://github.com/ikomom/viewport-editor.git](url) my project is here. thank a lot

**Comment by ymchun** [comment]
you mean your lib using `@vue/composition-api` didn't work in your another project?
do you have a minimal re-produce repo?

**Comment by ikomom** [comment]
thank you to your reply, i work it last night
